name: Solar System Workflow

on: push
    
jobs:
    first_job:
      runs-on: ubuntu-22.04
      steps:
        - name: list files
          run: ls
        - name: read file
          run: cat README.md
          