name: Deploying Solar System Application

on:
  push:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: List the files
        run: ls -l