name: Deploying Solar System Application



on:
  push:
    branches:
      - main

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: saadzahid/solarsystem-mongodb-test:01
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://test-user:test-user-1@localhost:27017/solar_system

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
