name: Deploying Solar System Application

on:
  push:
    branches:
      - main

jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install

      - name: Testing 
        run: npm test